# Generated by Django 5.0.11 on 2025-03-06 21:55

import bazis.contrib.bg.models
from django.db import migrations, models
from django.utils.translation import gettext_lazy as _



class Migration(migrations.Migration):

    dependencies = [
        ('bg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=bazis.contrib.bg.models.task_file_name, verbose_name='File'),
        ),
    ]
