# Generated by Django 5.0.11 on 2025-07-28 14:02

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _



class Migration(migrations.Migration):

    dependencies = [
        ('bg', '0002_alter_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='phase',
            field=models.CharField(max_length=1024, verbose_name='Phase'),
        ),
    ]
