# Generated by Django 6.0.1 on 2026-07-01 19:44

import bazis.core.utils.orm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg', '0003_alter_task_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='performed',
            field=models.JSONField(blank=True, encoder=bazis.core.utils.orm.JsonFieldEncoder, null=True, verbose_name='Performed'),
        ),
    ]
