# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 6.0.1 on 2026-07-01 19:44

import bazis.core.utils.orm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg', '0003_alter_task_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='performed',
            field=models.JSONField(blank=True, encoder=bazis.core.utils.orm.JsonFieldEncoder, null=True, verbose_name='Performed'),
        ),
    ]
