# Generated by Django 6.1.1 on 2026-10-01 09:34

import bazis.contrib.bg.models_abstract
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bg", "0004_alter_task_performed"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="task",
            new_name="bg_task_state_fin",
            old_fields=("state", "dt_finish"),
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="bg_task_cls_state",
            old_fields=("cls_path", "state"),
        ),
        migrations.AlterField(
            model_name="task",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=bazis.contrib.bg.models_abstract.get_task_storage,
                upload_to=bazis.contrib.bg.models_abstract.task_file_name,
                verbose_name="File",
            ),
        ),
    ]
