# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 6.1.1 on 2026-10-01 09:34

import bazis.contrib.bg.models_abstract
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bg", "0004_alter_task_performed"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="task",
            new_name="bg_task_state_fin",
            old_fields=("state", "dt_finish"),
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="bg_task_cls_state",
            old_fields=("cls_path", "state"),
        ),
        migrations.AlterField(
            model_name="task",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=bazis.contrib.bg.models_abstract.get_task_storage,
                upload_to=bazis.contrib.bg.models_abstract.task_file_name,
                verbose_name="File",
            ),
        ),
    ]
